[package]
name = "uexec"
version = "0.1.0"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
edition = "2018"

[dependencies]
async-channel = "^1.6"
crossbeam-utils = "^0.8"
fastrand = "^1.4"
futures-core = "^0.3"
once_cell = "^1.7"
parking_lot = "^0.11"
