[package]
name = "uexec"
version = "0.1.0"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
edition = "2018"

[dependencies]
async-channel = "^1.6"
fastrand = "^1.4"
parking_lot = "^0.11"
